<a href="https://colab.research.google.com/github/zyr1on/dataStructure-Project/blob/main/Numpy_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy array oluşturma


In [ ]:
#arrayler çok boyutlu dizile olarak düşünülebilir.
#array oluşturmanın 3 farklı yolu vardır.
#1)liste yada tuple benzeri nesneleri arreye döndürebiliriz.          np.array([1,2,3])
#2)built in hazır fonksiyonlar yardımı ile oluşturabiliriz            np.arange(),np.linspace()vb.
#3)rastgele data üreterek                                             np.random modülü içindeki fonksiyonlar ile

In [ ]:
import numpy as np
arr1d=np.array([1,2,3])
arr1d

array([1, 2, 3])

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
array=np.arange(1,100,2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
#np.linspace() fonksiyonu ile hızlıca arrayler oluşabilir
np.linspace(10,100,10) # endpoint bunda dahil

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.logspace(1,3,5) # 10**1 ile 10**3 arasında 5 tane logaritmik artış yapan array oluşturdu



array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
array=np.linspace(10,100,19)
array
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
import numpy as np
array0=np.linspace(0,1000,26)
array0

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [ ]:
np.zeros((2,3)) # boş bir array oluşturuyor sıfırlardan oluşan

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:

 np.ones((2,3)) # birlerden oluşan bir array oluşturur.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(5) # 5 e 5 bir birim matris oluşturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.rand(5)# rand fonksiyonu ile rastgele sayılar oluşturur. dönen değerler 0-1 arasında.

array([0.28141453, 0.22904096, 0.34095085, 0.46742445, 0.97432595])

In [ ]:
np.random.rand(2,5)

array([[0.00329796, 0.36309463, 0.72410074, 0.70131533, 0.5160329 ],
       [0.01679244, 0.26037095, 0.94818429, 0.09470774, 0.35036175]])

In [ ]:
np.random.rand(2,5)*10

array([[9.85203464, 9.78555313, 0.11244602, 5.27009054, 6.3938305 ],
       [8.82789173, 4.97908695, 8.06002243, 8.76752961, 1.54410295]])

In [ ]:
np.random.randint(15,50,5)#random int sayı çağırır. 15 ile 50 arasında rastgele 5 sayı üret

array([18, 26, 26, 29, 23])

In [ ]:
np.random.randint(15,50,(3,5))

array([[38, 49, 18, 34, 27],
       [21, 16, 15, 36, 49],
       [49, 47, 36, 40, 26]])

In [2]:
np.random.randint(0,50,(4,6))

array([[ 4, 15, 35, 13, 12, 39],
       [ 4,  9, 31, 17, 26, 35],
       [10, 12, 20, 10, 32,  6],
       [ 0, 15, 22, 12, 37,  1]])

#Arrayın boyut sayısını ve Shapeini kontrol etmek

In [ ]:
#.ndim attribute i ile arayımızın kaç boyutlu olduğuna bakabiliriz

In [ ]:
arr1d=np.array([1,2,3])
arr1d.ndim

1

In [1]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d.ndim
arr2d.shape


(2, 3)

#Numpy arraylerini indeskleme ve ögelerime erişme

In [3]:
arr1d=np.array([1,2,3])
arr1d[0]

np.int64(1)

In [7]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d[1,2]

np.int64(6)

In [12]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]]])
arr3d[0,3,2]

np.int64(13)

In [16]:
arrayö=np.arange(53,62)
arrayö[4]

np.int64(57)

#NumPy dizilerinde maximum ve minimum elemanlarına ve bu elemanların indexlerine erişme

In [20]:
arr=np.random.randint(1,100,10)
print(arr)
arr.max()
arr.argmax()#maksimum değerin indeksini çağırır


[21 76 48 75 80 94 76 29 60  1]


np.int64(5)

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.argmin()

np.int64(9)

#Numpy arraylerinde slicing (dilimleme)

In [28]:
arr=np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [31]:
arr[5:11] # iki nokta kullandık ,dilimleme

array([55, 56, 57, 58, 59, 60])

In [37]:
arr[-5:]


array([60, 61, 62, 63, 64])

In [38]:
arr[2:10:2]# son değer kaçar kaçar gideceğini gösteriyor

array([52, 54, 56, 58])

In [40]:
arr[5:11]=999 #Broadcasting
arr

array([ 50,  51,  52,  53,  54, 999, 999, 999, 999, 999, 999,  61,  62,
        63,  64])

In [45]:
arr=np.arange(-30,11)

arr[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

# Bir arrayin veri türünü kontrol etme

In [ ]:
#.dtype attribute ile arrayımızın data type kontrol edilebilir

In [51]:
arr=np.arange(0,10)
arr



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:

arr.dtype

dtype('int64')

In [54]:
arr=np.arange(0,100,dtype="float")
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [55]:
arr.dtype

dtype('float64')

# bir arrayın dtype nı değiştirme

In [61]:
arr=np.array([1.2,1.5,2.5,5.7])
arr.dtype


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
#.astype ile arrayların type değişir

In [62]:
arr.astype("int")

array([1, 1, 2, 5])

In [65]:
arr=np.array(['1','5','8','9','11'])
arr

array(['1', '5', '8', '9', '11'], dtype='<U2')

In [69]:
arr.dtype
arr=arr.astype("int")


In [70]:
arr.dtype

dtype('int64')

#